apiVersion: skaffold/v3
kind: Config
build:
 artifacts:
  - image: gallerenfeld/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: 'src/**/*.js'
  - image: gallerenfeld/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '*.js'
  - image: gallerenfeld/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '*.js'
  - image: gallerenfeld/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '*.js'
  - image: gallerenfeld/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '*.js'
  - image: gallerenfeld/query
    context: query
    sync:
      manual:
        - dest: .
          src: '*.js'
    docker:
      dockerfile: Dockerfile
manifests:
 rawYaml:
 - ./infra/k8s/*
deploy:
 kubectl: {}